### ISSUE TITLE
Create question catalogue for podcast hosts

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#26]
https://docs.google.com/document/d/1k9Gg_-bB8iN8VKXXXVW6oRy_2FWdmpRuK_7BSEPmFIk/edit

**Comment by woolfg** [comment]
basic draft created, @mre can you please check, so we can upload it in an md file to the roadmap repo

**Comment by mre** [comment]
Sounds good. Converted it to a Markdown document:
https://github.com/openpodcast/roadmap/blob/master/SURVEY.md
It can also serve as a template while conducting more interviews as mentioned in the description.
From my side we can close this.

**Comment by woolfg** [comment]
sync between google docs updates and question catalog is needed

**Comment by mre** [comment]
done
