### ISSUE TITLE
Finish all APIs using the connector for Spotify

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#55]
Connector Podcast (+send to API):

- [x] metadata (not time bound, alltime)
- [x] episodes (pagination -> fetch all episodes) 
- [x] detailedStreams (3 days)
- [x] listeners (3 days) https://github.com/openpodcast/api/issues/20
- [x] aggregate (3x1 days (today, yesterday, the day before yesterday) as otherwise you get aggregated data of 3 days)
- [x] followers (3 days)

Connector Episode (+send to API):

- [x] detailedStreams (3 days) https://github.com/openpodcast/api/issues/18
- [x] listeners (3 days)
- [x] aggregate (3x1 days (today, yesterday, the day before yesterday) as otherwise you get aggregated data of 3 days)
- [x] performance (alltime)

API Podcast:

- [x] metadata https://github.com/openpodcast/api/pull/15
- [x] episodes
- [x] detailedStreams
- [x] listeners
- [x] aggregate  https://github.com/openpodcast/api/pull/17
- [x] followers

API Episode:

- [x] detailedStreams
- [x] listeners
- [x] aggregate https://github.com/openpodcast/api/issues/14
- [x] performance

**Comment by woolfg** [comment]
detailedStreams in API in https://github.com/openpodcast/api/commit/f4294906b65725984f51a6141593972f93bb8e7d implemented

**Comment by mre** [comment]
Added the last remaining endpoint: followers. With that we're done here for now I think.
