### ISSUE TITLE
Integrate Apple Podcaster Data in conector and fetch data

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#56]
APIs:

- [x] /analytics/episodes?showId=1642486726&date=2017-09-19&mode=ALL_TIME Episode Metadata
- [x] /analytics/showOverviewV3?showId=1603082924&start=2017-09-19&end=2022-10-27&mode=ALL_TIME&seriesMode=MONTHLY Overview numbers
- [x] episodeDetails?startDate=2017-09-17&endDate=2021-04-20&showId=1603082924&episodeId=1000583770577&mode=ALL_TIME Episode details (countries, cities, consumption)
- [x] analytics/showTrendsV2?showId=1603082924&start=2022-08-08&end=2022-08-14&mode=WEEKLY&seriesMode=DAILY&metric=PLAYS&dimension=BY_EPISODES) daily metrics, 16 dimensions which can be even broke down further, e.g. episode listens in germany by enganged users
  - [x] followers, listeners, plays, time listended
  - [x] grouped by episode, country, city, follow status, engagement

**Comment by mre** [comment]
Started working on Apple connector here: https://github.com/openpodcast/apple-connector

#### Integrated endpoints so far:
* showOverviewV3
* episodes

**Comment by woolfg** [comment]
>     * episodes (Notably doesn't support any pagination. I wonder if they always return all episodes even for podcasts with many episodes.)

for EngKiosk with 43 episodes they return all.

**Comment by mre** [comment]
Creating PR for `open` repo next

**Comment by woolfg** [comment]
https://github.com/openpodcast/api/pull/24

**Comment by woolfg** [comment]
trends api fully covered by https://github.com/openpodcast/api/pull/25

**Comment by woolfg** [comment]
all required apis covered
