### ISSUE TITLE
docker compose setup of whole stack

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#63]
the openpodcast stack should be usable by spinning up a docker compose stack. all needed creds should be provided by env variables

- [x] add mysql to docker compose (use public image)
- [x] create image on dockerhub and add api to docker compose
- [x] create image on dockerhub and add apple auth automation to docker compose
- [x] create image on dockerhub and add connector + cron to docker compose
- [x] add anlytics metabase (use public image)

**Comment by mre** [comment]
I'm assuming we'll add all components via Docker images. If so, maybe we could set up pipelines for the projects to push to Dockerhub. We'd need a namespace on Dockerhub for that, e.g. `openpodcast`, which is still available.
Maybe fixed release versions will make it into the setup (and not nightly builds). This way we can make sure the components of the stack always work well together.

The alternative would be to create a monorepo (or use submodules), but I don't think we should do that.

**Comment by woolfg** [comment]
> I'm assuming we'll add all components via Docker images. If so, maybe we could set up pipelines for the projects to push to Dockerhub. 

created a dockerhub account and namespace openpodcast

**Comment by mre** [comment]
Created https://github.com/openpodcast/stack; adding mysql first.

**Comment by mre** [comment]
API added. Copied over the `schema.sql` for now. We should discuss where to fetch it from later.

**Comment by woolfg** [comment]
wer can just share the SQL file between containers using volumes as long as it is present in the API image.

**Comment by mre** [comment]
Added Metabase. The container does get stuck sometimes and needs a restart. Maybe it has something to do with the database not being up when it tries to initialize. Something we should investigate.

**Comment by mre** [comment]
Added final component, apple-automation to [stack](https://github.com/openpodcast/stack). Tested locally and works as expected. 🥳
