### ISSUE TITLE
screenshots/video on current landing page

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#64]

**Comment by woolfg** [comment]
https://github.com/openpodcast/website/commit/d58580036ec978f8d8047e967524716217db85bd
https://github.com/openpodcast/website/commit/8026da4d2135bde778e4a9d24e7cc7b02a59abfd
https://github.com/openpodcast/website/commit/e60ea5dd95e89bd3f4e356daf4fdf7537fde7685

**Comment by woolfg** [comment]
@mre I am still getting this error sometimes on the github page 

![Image](https://user-images.githubusercontent.com/1328269/204529605-5e9904a8-9b6d-4b8b-af0a-de5c06b1d263.png)

**Comment by mre** [comment]
Uploaded a new version. Can you clear the cache and try again?
