### ISSUE TITLE
AppleTrendsEpisodeListeners is empty

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#68]
the api `showTrends/Listeners` is not served by the connector yet

**Comment by woolfg** [comment]
`showTrends/Followers` and `showTrends/Listeners` missing

see https://github.com/openpodcast/api/blob/main/fixtures/appleTrendsListenersByEpisode.json and https://github.com/openpodcast/api/blob/main/fixtures/appleTrendsFollowers.json

fyi:

- Listeners/by Episode -> fills tables `appleTrendsEpisodeListeners` and `appleTrendsPodcastListeners`
- Followers -> fills table `appleTrendsPodcastFollowers`
- Plays/by Episode -> covered by Listeners/by Episode (duplicated)
- Time listened/by Episode -> covered by Listeners/by Episode (duplicated)

**Comment by mre** [comment]
* Pull request for `open`: https://github.com/openpodcast/open/pull/10
* Apple Auth is currently failing. Pull request to try and fix that: https://github.com/openpodcast/apple-automation/pull/6

**Comment by mre** [comment]
This is fixed. 🎉
