### ISSUE TITLE
Create pipeline monitoring

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#72]
The pipeline to import data can fail from time to time. We have multiple options:

- send information if error encountered in connector run (could be done in github actions?)
- run SQL check queries to monitor if everything is up and running? maybe some healthcheck endpoints in the api which can be then triggered by a daily monitoring test form outside

could be added to `/status` endpoint

**Comment by mre** [comment]
As for the first part, we could set up [Slack notifications for failed actions](https://dev.to/ravgeetdhillon/send-slack-notification-when-github-actions-fails-1ba6)

**Comment by woolfg** [comment]
added a test metabase alert

**Comment by woolfg** [comment]
adapt dashboard api to be able to monitor by e.g. grafana cloud
