### ISSUE TITLE
Prototype of down/upvote

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#74]
Quick prototype of the first external Open API using shownotes

- [ ] how to identify an episode?
- [x] prevent dowuble votes by hashing agent+ip
- [x] schema to store up/downvotes
- [x] api endpoint to count up/downvotes
-

**Comment by mre** [comment]
>  how to identify an episode?

Guess the easiest would be to hardcode the links in the show notes, e.g. http://api.openpodcast.dev/feedback?show=xx&episode=14&vote=up where `xx` is the Podcast ID and `14` is the episode number.

Another option is to use the forwarder:
The show notes are in the RSS feed, so what if we analyze the links in the show notes and add the episode number to any upvote/downvote link we find?

**Comment by woolfg** [comment]
good point :+1: , for now I guess the hard coded link is the simplest solution. later we can add it in an xml element as well (Open Standard)

**Comment by woolfg** [comment]
https://github.com/openpodcast/api/pull/35

**Comment by woolfg** [comment]
close as main feature is done. the question how to identify an episode is still open in #80
