### ISSUE TITLE
test stack documentation, sql schema import

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#77]
- [x] docs ok? is everything clear to start up a stack to try out the solution
- [x] mysql schema import from api image? can we simplify this?

**Comment by mre** [comment]
Extended the docs a bit 
* on the website (https://github.com/openpodcast/website/commit/fd69cc5edca36b08ade7beb5b5e90cb9625b805f)
* for the stack (https://github.com/openpodcast/stack/commit/900722b45dc6861ed625f3bcf3790b3963b92303)
* for apple-automation (https://github.com/openpodcast/apple-automation/commit/37ce3a80f79ed3ee1a3c0fd66eafb1dda3edc08a)

Not perfect, but it's a start.

**Comment by woolfg** [comment]
multiple inconsistencies found and fixed in openpodcast/#24

**Comment by woolfg** [comment]
first client onboarded. changes has to be applied to public `stack` repo #90
