### ISSUE TITLE
Create web extension

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#78]
- finish web extension for chrome openpodcast/web-extension#1
- [x] submit extension for review to google chrome store

**Comment by mre** [comment]
Very nice!

**Comment by woolfg** [comment]
"This draft is pending review." can take several weeks....

**Comment by woolfg** [comment]
was more or less accepted -> @mre can you try it pls https://chrome.google.com/webstore/detail/openpodcast-extension/kdgmkjmggjefccigfbeidmaamhbfnkhh

**Comment by mre** [comment]
Works like a charm.

The workflow is still a bit cumbersome. I think we can add a link to openpodcast.dev/#connect to the extension (and maybe even redirect there when installing the extension. This would provide some guidance to new users.

Apart from that, very nice work!

**Comment by woolfg** [comment]
I would imagine the workflow as follows:

- user visits openpodcast.dev
- user gets information that for the keys, the extension has to be installed
- user installs extension
- keys are shown on the website, which is still open?
- in the future the keys should automatically taken by the website, without any copy effort
