### ISSUE TITLE
Onboard first test client

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#79]
- [x] database
- [x] metabase incl. https url
- [x] connector (cron)
- [x] apple auth
- [x] receive spotify/apple tokens from client -> send out email

**Comment by woolfg** [comment]
- Chrome extension ready, instructions on https://openpodcast.dev/#connect should work -> ready to send the data to the first client

**Comment by woolfg** [comment]
for the apple auth we use the current running endpoint -> maybe we need a proper auth/key?

**Comment by mre** [comment]
AFAICT this is done and can be closed.

**Comment by woolfg** [comment]
we still need a "running" stack for the client

**Comment by woolfg** [comment]
everything up and running. call with first client next week to explain everything
