### ISSUE TITLE
M1 Collect Feedback - overview issue

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#8]
- [x] At least 10 invites were sent out to podcast hosts and operators to ask for interviews
- [x] Pain points in the area of analytics of podcasts were collected (via interviews and research) and documented (if necessary incorporation of learnings into plans)

**Comment by woolfg** [comment]
interview Google sheet created "Podcast Interview Survey"

**Comment by woolfg** [comment]
5 people contacted so far, 3 interviews conducted

**Comment by mre** [comment]
Sent out tweet for bigger reach: https://twitter.com/OpenPodcastDev/status/1567444578499788800

**Comment by woolfg** [comment]
contacted so far, people behind:

- https://open.spotify.com/show/7vO8g4nPaUcT2ihQFmccl4
- https://growgetters.io/podcast#/
- https://xundy-podcast.de
- https://www.equalitymedia.de/
- https://twitter.com/nitramred
- https://podstars.de/
- https://stationista.com

**Comment by woolfg** [comment]
answered survey from herz-schmerz-frei https://angenommen-praxis.de copied into doc

**Comment by woolfg** [comment]
Martin Fischer contacted 
https://twitter.com/nitramred

Wendy Maguire contacted
https://www.secondwindthepodcast.com

**Comment by woolfg** [comment]
results documented in https://github.com/openpodcast/roadmap/blob/master/survey_outcome.md

**Comment by mre** [comment]
Contacted hosts of https://www.programmier.bar/.

**Comment by woolfg** [comment]
interviewed Wannabe Entrepreneur / Tiago https://wannabe-entrepreneur.com

**Comment by woolfg** [comment]
done. more feedback see #36 in next milestone
