### ISSUE TITLE
thumbs up/down not linked in spotify iOS

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#81]
reported by @brgmn

**Comment by mre** [comment]
Was thinking of using the HTML entities of thumbs up/down. If I insert them into Redcircle, they get shown as text, though. 🫤 Not sure if that is easily fixable.

**Comment by woolfg** [comment]
ios seems to be more strict and filters links (might be also the case for other ios apps such as the native apple podcast app)

-> asked ios person to reproduce the problem

**Comment by woolfg** [comment]
spotify on iOS removes icons
![Image](https://user-images.githubusercontent.com/1328269/212351347-30fe5625-3015-485b-89dd-dc67a8604298.png)

in native apple podcasts app it seems to work

![Image](https://user-images.githubusercontent.com/1328269/212351458-ec3fc596-0d0f-44d6-9c24-74e5f4c7fe92.png)

**Comment by woolfg** [comment]
for testing changed in episode



![Image](https://user-images.githubusercontent.com/1328269/212355619-80966fce-d556-4870-8f5d-daa3843753a0.png)

**Comment by woolfg** [comment]
it just works when there another character in the link to render.

**Comment by mre** [comment]
In this case I'd vote (heh) for either

* 👍 up 👎 down
* 👍 (upvote) 👎 (downvote)

**Comment by mre** [comment]
What's up with the last characters in the first line that aren't not bold? Rendering issue?
<img width="113" alt="image" src="https://user-images.githubusercontent.com/175809/212924837-b93cb20a-a5a0-412c-b747-b1ee0762d187.png">

**Comment by woolfg** [comment]
in general works, but we have to make sure to include chars...
