### ISSUE TITLE
management-interface (last import, last data received, etc)

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#82]
- what is the status of imports
- what is the last data that was imported

=> could be done in metabase for more details but would be also nice to have a quick overview without logging in to metabase. could be also helpful for debugging. maybe we enhance the /health endpoint a bit and also give some stats. this can be then fetched on a static webpage. 

suggested by @brgmn

**Comment by mre** [comment]
First step is to build the status API, which returns a JSON structure of all endpoints and the last updates (for the given account). Pull Request: https://github.com/openpodcast/api/pull/46

**Comment by woolfg** [comment]
closed by openpodcast/api#46
