### ISSUE TITLE
redcircle changed subdomains 

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#88]
RedCircle changed domain from
 https://stream.redcircle.com/episodes/7cce4a7c-8405-40c3-a9bf-dd902f0a07d8/stream.mp3

to
 https://audio1.redcircle.com/episodes/7cce4a7c-8405-40c3-a9bf-dd902f0a07d8/stream.mp3

do we have to change something? webpage, forwarder or similar?

**Comment by mre** [comment]
Yes, I see three locations:
* [ ] forwarder
* [ ] stack fixtures
* [ ] api fixtures

Creating PRs for those.

**Comment by mre** [comment]
That said, the old URLs still work? So technically we don't have to change anything (yet).
Interestingly they also use audio2.redcircle.com; at least that's what I see in https://feeds.redcircle.com/2c2cd740-1c1f-4928-adac-98a692dbf4c2 at the moment. Probably some load-balancing.

**Comment by woolfg** [comment]
ok, then we have to dynamically add it to the url somehow

**Comment by woolfg** [comment]
where is it neede in stack and api?

**Comment by mre** [comment]
Just the fixtures that might need updating. We could also keep those, though.

**Comment by woolfg** [comment]
we ignore it for now due to prio on importers
