### ISSUE TITLE
M1 Data model & visualization requirements - overview issue

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#9]
- [x] Tracked data: Details of the tracking process (e.g. according to IAB standards, what data has to be collected and how) are documented and published
- [x] Analytics Dashboard: List of required  visualizations in the podcast realm was created and published (partially sourced from the interviews of podcast hosts)
- [x] OpenAPI: Definition of possible trackable events via the open API is published on high level (no detailed API specification yet as it is the basis for further discussion with partners and podcast hosts)

What metrics do exist and what do we want to implement?

**Comment by mre** [comment]
We started collecting the tracked data we plan to support here:
https://docs.google.com/document/d/1tnfyh4SIP8ONd3KtjmKv-P9_zlLMP0SCo9Y1h-2e4pE
The document will be moved to a separate repository after some internal review.

**Comment by woolfg** [comment]
also documented in https://docs.google.com/spreadsheets/d/1ADWH9U3jIGBf3XpJssG6CQxA6NDGquUgJP-e93z2lW4/edit#gid=0
