### ISSUE TITLE
Hackernews post

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#96]

**Comment by mre** [comment]
What do you think of a "Show HN" post?

Title: "Introducing OpenPodcast: A Google Analytics for Podcasts"

Post Body:

We are excited to announce the launch of OpenPodcast, an open platform for podcast analytics. With OpenPodcast, podcasters can get insights and performance metrics similar to what they get from Google Analytics, but specifically designed for podcasts.

OpenPodcast currently supports Apple Podcasts and Spotify, and we plan to extend support to more endpoints in the future. If you're interested in contributing to the platform, we'd love to hear from you! Our code is open-source and available on GitHub (https://github.com/openpodcast).

With OpenPodcast, you can track your podcast's performance and see how your episodes are performing over time. You can see your listeners' behavior, such as how long they listen, age and gender, and which episodes are their favorites. 

The data is stored in a plain old MySQL database and can be accessed and analyzed easily. 
You can run the full stack yourself using Docker images or each out to us and we'll set up a hosted demo for you.

We believe that OpenPodcast will be a valuable tool for podcasters and help them grow their audience and improve their podcast's performance. Give it a try and let us know what you think!
We're curious about your feedback.

**Comment by woolfg** [comment]
follow up on https://docs.google.com/document/d/1GK9yITzA_52UHqiBvJh9N4jDbFeZN83L0QmlEKdcPko/edit

**Comment by woolfg** [comment]
https://news.ycombinator.com/item?id=34763961
